/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AppWeatherRouteImport } from './routes/_app.weather'
import { Route as AppTradeToolsRouteImport } from './routes/_app.trade-tools'
import { Route as AppSuppliersRouteImport } from './routes/_app.suppliers'
import { Route as AppShipmentsRouteImport } from './routes/_app.shipments'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppRfqRouteImport } from './routes/_app.rfq'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppQuotationsRouteImport } from './routes/_app.quotations'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppOrdersRouteImport } from './routes/_app.orders'
import { Route as AppNovaAiRouteImport } from './routes/_app.nova-ai'
import { Route as AppMarketRouteImport } from './routes/_app.market'
import { Route as AppInvoicesRouteImport } from './routes/_app.invoices'
import { Route as AppIntegrationsRouteImport } from './routes/_app.integrations'
import { Route as AppExportRouteImport } from './routes/_app.export'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppBuyersRouteImport } from './routes/_app.buyers'
import { Route as AppAnalyticsRouteImport } from './routes/_app.analytics'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWeatherRoute = AppWeatherRouteImport.update({
  id: '/weather',
  path: '/weather',
  getParentRoute: () => AppRoute,
} as any)
const AppTradeToolsRoute = AppTradeToolsRouteImport.update({
  id: '/trade-tools',
  path: '/trade-tools',
  getParentRoute: () => AppRoute,
} as any)
const AppSuppliersRoute = AppSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AppRoute,
} as any)
const AppShipmentsRoute = AppShipmentsRouteImport.update({
  id: '/shipments',
  path: '/shipments',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRfqRoute = AppRfqRouteImport.update({
  id: '/rfq',
  path: '/rfq',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppQuotationsRoute = AppQuotationsRouteImport.update({
  id: '/quotations',
  path: '/quotations',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersRoute = AppOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AppRoute,
} as any)
const AppNovaAiRoute = AppNovaAiRouteImport.update({
  id: '/nova-ai',
  path: '/nova-ai',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketRoute = AppMarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesRoute = AppInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegrationsRoute = AppIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AppRoute,
} as any)
const AppExportRoute = AppExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppBuyersRoute = AppBuyersRouteImport.update({
  id: '/buyers',
  path: '/buyers',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/analytics': typeof AppAnalyticsRoute
  '/buyers': typeof AppBuyersRoute
  '/dashboard': typeof AppDashboardRoute
  '/export': typeof AppExportRoute
  '/integrations': typeof AppIntegrationsRoute
  '/invoices': typeof AppInvoicesRoute
  '/market': typeof AppMarketRoute
  '/nova-ai': typeof AppNovaAiRoute
  '/orders': typeof AppOrdersRoute
  '/profile': typeof AppProfileRoute
  '/quotations': typeof AppQuotationsRoute
  '/reports': typeof AppReportsRoute
  '/rfq': typeof AppRfqRoute
  '/settings': typeof AppSettingsRoute
  '/shipments': typeof AppShipmentsRoute
  '/suppliers': typeof AppSuppliersRoute
  '/trade-tools': typeof AppTradeToolsRoute
  '/weather': typeof AppWeatherRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/analytics': typeof AppAnalyticsRoute
  '/buyers': typeof AppBuyersRoute
  '/dashboard': typeof AppDashboardRoute
  '/export': typeof AppExportRoute
  '/integrations': typeof AppIntegrationsRoute
  '/invoices': typeof AppInvoicesRoute
  '/market': typeof AppMarketRoute
  '/nova-ai': typeof AppNovaAiRoute
  '/orders': typeof AppOrdersRoute
  '/profile': typeof AppProfileRoute
  '/quotations': typeof AppQuotationsRoute
  '/reports': typeof AppReportsRoute
  '/rfq': typeof AppRfqRoute
  '/settings': typeof AppSettingsRoute
  '/shipments': typeof AppShipmentsRoute
  '/suppliers': typeof AppSuppliersRoute
  '/trade-tools': typeof AppTradeToolsRoute
  '/weather': typeof AppWeatherRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/buyers': typeof AppBuyersRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/export': typeof AppExportRoute
  '/_app/integrations': typeof AppIntegrationsRoute
  '/_app/invoices': typeof AppInvoicesRoute
  '/_app/market': typeof AppMarketRoute
  '/_app/nova-ai': typeof AppNovaAiRoute
  '/_app/orders': typeof AppOrdersRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/quotations': typeof AppQuotationsRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/rfq': typeof AppRfqRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/shipments': typeof AppShipmentsRoute
  '/_app/suppliers': typeof AppSuppliersRoute
  '/_app/trade-tools': typeof AppTradeToolsRoute
  '/_app/weather': typeof AppWeatherRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/analytics'
    | '/buyers'
    | '/dashboard'
    | '/export'
    | '/integrations'
    | '/invoices'
    | '/market'
    | '/nova-ai'
    | '/orders'
    | '/profile'
    | '/quotations'
    | '/reports'
    | '/rfq'
    | '/settings'
    | '/shipments'
    | '/suppliers'
    | '/trade-tools'
    | '/weather'
    | '/api/chat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/analytics'
    | '/buyers'
    | '/dashboard'
    | '/export'
    | '/integrations'
    | '/invoices'
    | '/market'
    | '/nova-ai'
    | '/orders'
    | '/profile'
    | '/quotations'
    | '/reports'
    | '/rfq'
    | '/settings'
    | '/shipments'
    | '/suppliers'
    | '/trade-tools'
    | '/weather'
    | '/api/chat'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/register'
    | '/_app/analytics'
    | '/_app/buyers'
    | '/_app/dashboard'
    | '/_app/export'
    | '/_app/integrations'
    | '/_app/invoices'
    | '/_app/market'
    | '/_app/nova-ai'
    | '/_app/orders'
    | '/_app/profile'
    | '/_app/quotations'
    | '/_app/reports'
    | '/_app/rfq'
    | '/_app/settings'
    | '/_app/shipments'
    | '/_app/suppliers'
    | '/_app/trade-tools'
    | '/_app/weather'
    | '/api/chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/weather': {
      id: '/_app/weather'
      path: '/weather'
      fullPath: '/weather'
      preLoaderRoute: typeof AppWeatherRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/trade-tools': {
      id: '/_app/trade-tools'
      path: '/trade-tools'
      fullPath: '/trade-tools'
      preLoaderRoute: typeof AppTradeToolsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/suppliers': {
      id: '/_app/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof AppSuppliersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/shipments': {
      id: '/_app/shipments'
      path: '/shipments'
      fullPath: '/shipments'
      preLoaderRoute: typeof AppShipmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rfq': {
      id: '/_app/rfq'
      path: '/rfq'
      fullPath: '/rfq'
      preLoaderRoute: typeof AppRfqRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quotations': {
      id: '/_app/quotations'
      path: '/quotations'
      fullPath: '/quotations'
      preLoaderRoute: typeof AppQuotationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders': {
      id: '/_app/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AppOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/nova-ai': {
      id: '/_app/nova-ai'
      path: '/nova-ai'
      fullPath: '/nova-ai'
      preLoaderRoute: typeof AppNovaAiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/market': {
      id: '/_app/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof AppMarketRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices': {
      id: '/_app/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AppInvoicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/integrations': {
      id: '/_app/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AppIntegrationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/export': {
      id: '/_app/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof AppExportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/buyers': {
      id: '/_app/buyers'
      path: '/buyers'
      fullPath: '/buyers'
      preLoaderRoute: typeof AppBuyersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppBuyersRoute: typeof AppBuyersRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppExportRoute: typeof AppExportRoute
  AppIntegrationsRoute: typeof AppIntegrationsRoute
  AppInvoicesRoute: typeof AppInvoicesRoute
  AppMarketRoute: typeof AppMarketRoute
  AppNovaAiRoute: typeof AppNovaAiRoute
  AppOrdersRoute: typeof AppOrdersRoute
  AppProfileRoute: typeof AppProfileRoute
  AppQuotationsRoute: typeof AppQuotationsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppRfqRoute: typeof AppRfqRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppShipmentsRoute: typeof AppShipmentsRoute
  AppSuppliersRoute: typeof AppSuppliersRoute
  AppTradeToolsRoute: typeof AppTradeToolsRoute
  AppWeatherRoute: typeof AppWeatherRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppBuyersRoute: AppBuyersRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppExportRoute: AppExportRoute,
  AppIntegrationsRoute: AppIntegrationsRoute,
  AppInvoicesRoute: AppInvoicesRoute,
  AppMarketRoute: AppMarketRoute,
  AppNovaAiRoute: AppNovaAiRoute,
  AppOrdersRoute: AppOrdersRoute,
  AppProfileRoute: AppProfileRoute,
  AppQuotationsRoute: AppQuotationsRoute,
  AppReportsRoute: AppReportsRoute,
  AppRfqRoute: AppRfqRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppShipmentsRoute: AppShipmentsRoute,
  AppSuppliersRoute: AppSuppliersRoute,
  AppTradeToolsRoute: AppTradeToolsRoute,
  AppWeatherRoute: AppWeatherRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
